### ISSUE TITLE
No dist folder in npm

### ISSUE THREAD

**Issue by faizan-hasan** [Tony133/nestjs-knexjs#313]
@Tony133 There is no `dist` directory in npm package v0.0.7, version 0.0.6 has it
see https://registry.npmjs.org/nest-knexjs/-/nest-knexjs-0.0.7.tgz

**Comment by Tony133** [comment]
I forgot to do `npm run build` before `npm run publish`, my mistake, I apologize, use the `0.0.6` as well, every day I publish the `0.0.8`.

Thanks for the reporting  👍

**Comment by Tony133** [comment]
Released version `0.0.8`, let me know if everything works.

sorry again

**Comment by faizan-hasan** [comment]
LGTM, Thanks
