### ISSUE TITLE
Centralized KnexJS configuration

### ISSUE THREAD

**Issue by luukvhoudt** [Tony133/nestjs-knexjs#698]
Is it possible to avoid the declaration of a `knexfile.js` and make the migrations and seeds work? 

I would like to keep the Knex configuration in the AppModule's imports only.

**Comment by Tony133** [comment]
If it's not written in the documentation I don't think it's possible, this package works with all the configurations written in the official documentation.

Even some ORMs like TypeORM have this "double" configuration unfortunately for migrations.

**Comment by luukvhoudt** [comment]
Fair, however, it's true that you only need the `knexfile.js` for migrations and seeds right?

**Comment by Tony133** [comment]
Yes, to start the "up" and "down" migrations and use the seeds we need the "knexfile.js" file, let's say it is "tied" to the Knex CLI.

**Comment by luukvhoudt** [comment]
Alright, so this package is only responsible for the injection of knex connection into Nest? Just like [this package of Sviatoslv](https://github.com/svtslv/nestjs-knex).

**Comment by Tony133** [comment]
Yes, exactly and you can use all the configurations written in the official documentation, it is a wrapper package around knexjs, like all nestjs packages.

I created it for business reasons and also to understand step by step how to create a package for nestjs, you know sometimes you have to experiment a little bit to understand some things. 😄 

However, you can use knex even without packages, these are more packages  "nestjs style" (at least I call them that 😄 ) an alternative to creating a database provider custom with loggers in case of failed connection etc. , then it makes the code a little beautiful to look at.
