### ISSUE TITLE
Is NPM Package updated?

### ISSUE THREAD

**Issue by OliveiraCleidson** [Tony133/nestjs-knexjs#789]
# Is NPM Package updated?

I will use this package in a commercial application, but I don't know if this package is updated in the NPM registry, because the last commit was in a few days, but NPM was updated 2 years old. I'm installing directly from GitHub and not from NPM because of this.

**Comment by Tony133** [comment]
Hi @OliveiraCleidson, 
Yes, I keep it up to date. 
On NPM it is up to date, in fact the last commit was a month ago when I did the last release, version 0.0.14 ( see screenshot ), it is synchronized with Github. I will do another one soon to update the dependencies.

<img width="1682" alt=" screenshot" src="https://user-images.githubusercontent.com/11542387/227807620-9d10eaab-4f89-4714-ad60-a531f41abd6a.png">
